name: iepub
description: epub
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

isar_version: &isar_version 3.0.2

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/xml
  xml: ^6.1.0
  # https://pub.dev/packages/archive
  archive: ^3.3.1
  # https://pub.dev/packages/path_provider
  path_provider: ^2.0.11
  # https://pub.dev/packages/isar
  isar: *isar_version
  isar_flutter_libs: *isar_version


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.1
  isar_generator: *isar_version

flutter:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
