name: proxyfrpc
description: A new Flutter project.
version: 0.0.1+2
homepage: https://github.com/iptodays/packages

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  socks5_proxy: ^1.0.3+dev.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.iptodays.proxyfrpc
        pluginClass: ProxyfrpcPlugin
      ios:
        pluginClass: ProxyfrpcPlugin