name: ioader
description: 视频下载器
version: 0.0.1+4
homepage:

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: ">=1.17.0"

isar_version: &isar_version 3.0.2

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/dio
  dio: ^4.0.6
  # https://pub.dev/packages/path_provider
  path_provider: ^2.0.11
  # https://pub.dev/packages/isar
  isar: *isar_version
  isar_flutter_libs: *isar_version
  # https://pub.dev/packages/shelf
  shelf: ^1.4.0
  # https://pub.dev/packages/r_get_ip_v3
  r_get_ip_v3: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: *isar_version
  build_runner: ^2.2.1

flutter:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg