name: ioader
description: 视频下载器
version: 0.0.1+6
homepage: https://github.com/iptodays/packages

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/dio
  dio: ^4.0.6
  # https://pub.dev/packages/path_provider
  path_provider: ^2.0.11
  # https://pub.dev/packages/isar
  isar: ^3.0.2
  isar_flutter_libs: ^3.0.2
  # https://pub.dev/packages/shelf
  shelf: ^1.4.0
  # https://pub.dev/packages/r_get_ip
  r_get_ip: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  isar_generator: ^3.0.2
  build_runner: ^2.2.1