name: iwidgets
description: custom wiget
version: 0.0.4
homepage: https://github.com/iptodays/widgets

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/flutter_vibrate
  flutter_vibrate: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0