name: skan
description: SKAdNetwork
version: 0.0.1
homepage: https://github.com/iptodays/packages/tree/master/skan

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: SkanPlugin

platforms:
  ios: