name: imobile_ads
description: admob & unity
version: 0.0.3
homepage:

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/google_mobile_ads
  google_mobile_ads: ^2.0.0
  # https://pub.dev/packages/unity_ads_plugin
  unity_ads_plugin: ^0.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.iptoday.imobile_ads
        pluginClass: ImobileAdsPlugin
      ios:
        pluginClass: ImobileAdsPlugin
  # assets:
  #   - images/a_dot_burr.jpeg