name: imobile_ads
description: admob & unity
version: 0.0.7+8
homepage:

environment:
  sdk: ">=2.17.3 <3.0.0"
  flutter: ">=3.3.2"

dependencies:
  flutter:
    sdk: flutter
  # https://pub.dev/packages/google_mobile_ads
  google_mobile_ads: ^2.3.0
  # https://pub.dev/packages/unity_ads_plugin
  unity_ads_plugin: ^0.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.iptoday.imobile_ads
        pluginClass: ImobileAdsPlugin
      ios:
        pluginClass: ImobileAdsPlugin